services:
  ssh_server:
    hostname: ssh-server
    build:
      context: ./ssh_server
      dockerfile: Dockerfile
      args:
        USERNAME: test
        USER_UID: 1000
        USER_GID: 1000
        USER_PWD: test
    ports:
      - "127.0.0.1:22:22"
    container_name: ssh_server

  controller:
    build:
      context: ./controller
      dockerfile: Dockerfile
    volumes:
      - ./controller/nginx.yml:/etc/ansible/nginx.yml
      - ./controller/inventory:/etc/ansible/inventory
      - ./controller/ssh:/etc/ansible/ssh
    container_name: ansible
    stdin_open: true
    tty: true
