services:
  ssh_server:
    hostname: ssh-server
    build:
      context: ./ssh_server
      dockerfile: Dockerfile
      args:
        USERNAME: test
        USER_UID: 1000
        USER_GID: 1000
        USER_PWD: test
        
    ports:
      - "127.0.0.1:22:22"
    container_name: ssh_server

  controller:
    build:
      context: ./controller
      dockerfile: Dockerfile
    container_name: ansible
    stdin_open: true
    tty: true
      # Comment lancer le controller, sachant que les commandes pour lancer ce container ne sont absolument pas les mêmes?









  #backend:
  #  image: technical_interview/remote_connection
  #  build:
  #    context: backend
  #    dockerfile: ../backend.Dockerfile
#
  #custom:
  #  build: ~/custom


